version: "3"

services:
  go2:
    container_name: go2
    build: .
    ports:
      - "8125:8080"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: uwcs_go
      POSTGRES_USER: uwcs_go
      POSTGRES_PASSWORD: bananas
